#### Hi! Today you will play with NaN values and another Data Manipulation methods. Let us know if you need help and also if you need more challenges on that :)

#### The dataset that you will use is again recipes.csv. You can either use your own or the one in the subfolder "data". Do not forget to import the necessary libraries!

In [70]:
import pandas as pd
import numpy as np

df = pd.read_csv('data/recipes.csv')
print(df)

     Unnamed: 0  vegetarian  glutenFree  dairyFree  veryHealthy  healthScore  \
0             0        True        True       True        False          1.0
1             1        True        True      False        False          0.0
2             2       False       False      False        False          3.0
3             3        True       False       True        False          2.0
4             4       False        True      False        False         31.0
..          ...         ...         ...        ...          ...          ...
145         145       False        True       True        False         18.0
146         146        True       False      False        False          1.0
147         147        True        True       True         True         93.0
148         148        True        True      False        False          5.0
149         149        True        True       True         True        100.0

     aggregateLikes      id  \
0                 3  633998
1                 1  634426
2                 1  635085
3                 1  663229
4                 3  651437
..              ...     ...
145              13  638315
146               2  656248
147               2  637297
148               1  659412
149               4  647875

                                                 title  pricePerServing  ...  \
0                            Banana Blueberry Pancakes            55.79  ...
1              Basil and Orange Confit Compound Butter            15.07  ...
2                             Black Bottom Banana Bars            78.85  ...
3                  The Best Raw Chocolate Chip Cookies            54.64  ...
4                  Mediterranean Spinach Artichoke Dip           115.26  ...
..                                                 ...              ...  ...
145       Chicken Sausage, White Bean and Cabbage Soup           196.23  ...
146                                Pinot Noir Brownies            65.76  ...
147                          Cauliflower Chickpea Stew           139.28  ...
148  Saut√©ed Balsamic Green Beans With Cherry Tomatoes           101.81  ...
149        Indian-Style Dill and Turmeric Potato Salad           117.24  ...

     VitaminB3Amount  VitaminB3percentOfDailyNeed VitaminB1Amount  \
0               0.49                         2.44            0.03
1                NaN                          NaN             NaN
2               2.63                        13.13            0.32
3               0.65                         3.26            0.10
4               0.66                         3.29            0.07
..               ...                          ...             ...
145             0.53                         2.67            0.15
146             0.21                         1.07            0.03
147             4.77                        23.83            0.45
148             1.15                         5.73            0.12
149             0.21                         1.05             NaN

     VitaminB1percentOfDailyNeed  CalciumAmount  CalciumpercentOfDailyNeed  \
0                           2.26          18.11                       1.81
1                            NaN            NaN                        NaN
2                          21.09         100.80                      10.08
3                           6.47          26.79                       2.68
4                           4.64         162.84                      16.28
..                           ...            ...                        ...
145                        10.23         102.67                      10.27
146                         1.68          19.82                       1.98
147                        29.70         141.16                      14.12
148                         7.85          55.64                       5.56
149                          NaN          27.96                       2.80

     AlcoholAmount  AlcoholpercentOfDailyNeed  CaffeineAmount  \
0              NaN                        NaN             NaN
1              NaN                        NaN             NaN
2             0.28                       1.53            9.89
3              NaN                        NaN             NaN
4              NaN                        NaN             NaN
..             ...                        ...             ...
145            NaN                        NaN             NaN
146           2.48                      13.76           10.69
147            NaN                        NaN             NaN
148            NaN                        NaN             NaN
149            NaN                        NaN             NaN

     CaffeinepercentOfDailyNeed
0                           NaN
1                           NaN
2                          3.30
3                           NaN
4                           NaN
..                          ...
145                         NaN
146                        3.56
147                         NaN
148                         NaN
149                         NaN

[150 rows x 79 columns]

#### Print the names of Columns that have null values

In [31]:
df.columns[df.isna().any()]

Index(['FiberAmount', 'FiberpercentOfDailyNeed', 'VitaminB6Amount',
       'VitaminB6percentOfDailyNeed', 'ManganeseAmount',
       'ManganesepercentOfDailyNeed', 'SeleniumAmount',
       'SeleniumpercentOfDailyNeed', 'PotassiumAmount',
       'PotassiumpercentOfDailyNeed', 'VitaminB2Amount',
       'VitaminB2percentOfDailyNeed', 'VitaminCAmount',
       'VitaminCpercentOfDailyNeed', 'PhosphorusAmount',
       'PhosphoruspercentOfDailyNeed', 'FolateAmount',
       'FolatepercentOfDailyNeed', 'VitaminB5Amount',
       'VitaminB5percentOfDailyNeed', 'MagnesiumAmount',
       'MagnesiumpercentOfDailyNeed', 'IronAmount', 'IronpercentOfDailyNeed',
       'VitaminKAmount', 'VitaminKpercentOfDailyNeed', 'CopperAmount',
       'CopperpercentOfDailyNeed', 'VitaminAAmount',
       'VitaminApercentOfDailyNeed', 'VitaminB12Amount',
       'VitaminB12percentOfDailyNeed', 'VitaminDAmount',
       'VitaminDpercentOfDailyNeed', 'ZincAmount', 'ZincpercentOfDailyNeed',
       'VitaminEAmount', 'VitaminEpercentOfDailyNeed', 'VitaminB3Amount',
       'VitaminB3percentOfDailyNeed', 'VitaminB1Amount',
       'VitaminB1percentOfDailyNeed', 'CalciumAmount',
       'CalciumpercentOfDailyNeed', 'AlcoholAmount',
       'AlcoholpercentOfDailyNeed', 'CaffeineAmount',
       'CaffeinepercentOfDailyNeed'],
      dtype='object')

#### Print the recipes with the highest number of aggregateLikes

In [32]:
mask = df["aggregateLikes"] == df["aggregateLikes"].max()
dframe = df[mask]
dframe

,Unnamed: 0,vegetarian,glutenFree,dairyFree,veryHealthy,healthScore,aggregateLikes,id,title,pricePerServing,...,VitaminB3Amount,VitaminB3percentOfDailyNeed,VitaminB1Amount,VitaminB1percentOfDailyNeed,CalciumAmount,CalciumpercentOfDailyNeed,AlcoholAmount,AlcoholpercentOfDailyNeed,CaffeineAmount,CaffeinepercentOfDailyNeed
50,50,False,True,True,False,4.0,16911,715419,Slow Cooker Spicy Hot Wings,101.43,...,7.42,37.09,0.08,5.0,44.21,4.42,NaN,NaN,NaN,NaN

#### Handle the missing values of ‚Äúcalcium percent of Daily need‚Äù. Sort the resulting DataFrame by id column.

In [33]:
mask = df["CalciumpercentOfDailyNeed"].isna() == True
df1 = df[mask]
df1.sort_values('id')

,Unnamed: 0,vegetarian,glutenFree,dairyFree,veryHealthy,healthScore,aggregateLikes,id,title,pricePerServing,...,VitaminB3Amount,VitaminB3percentOfDailyNeed,VitaminB1Amount,VitaminB1percentOfDailyNeed,CalciumAmount,CalciumpercentOfDailyNeed,AlcoholAmount,AlcoholpercentOfDailyNeed,CaffeineAmount,CaffeinepercentOfDailyNeed
1,1,True,True,False,False,0.0,1,634426,Basil and Orange Confit Compound Butter,15.07,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
74,74,True,False,False,False,0.0,1,634816,Beignets,19.00,...,NaN,NaN,0.02,1.21,NaN,NaN,NaN,NaN,NaN,NaN
71,71,False,True,True,False,1.0,1,640351,"Cranberry ""Cupcakes",31.80,...,NaN,NaN,0.04,2.63,NaN,NaN,NaN,NaN,NaN,NaN
25,25,False,False,False,False,0.0,1,654516,Pandan Thumbprint Biscuits,54.26,...,0.57,2.87,0.06,3.83,NaN,NaN,NaN,NaN,18.48,6.16
68,68,True,False,False,False,0.0,1,658823,Rosewater Lavender Shortbread,16.43,...,0.62,3.10,0.08,5.54,NaN,NaN,NaN,NaN,NaN,NaN
138,138,True,False,True,False,12.0,1,662315,"Sundried Tomato,Olive,Rosemary and Thyme Focca...",81.78,...,2.00,9.99,0.46,30.84,NaN,NaN,NaN,NaN,NaN,NaN
66,66,False,True,False,False,1.0,1,663885,Truffle Linguine With Tomatoes and Pancetta,11.09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
102,102,True,True,True,False,1.0,1,1095713,Coconut Flour Muffins,30.66,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

#### Delete the columns that have null values == 141

In [60]:
df1 = df.dropna(axis=1, thresh=141)
print(df1)

     Unnamed: 0  vegetarian  glutenFree  dairyFree  veryHealthy  healthScore  \
0             0        True        True       True        False          1.0
1             1        True        True      False        False          0.0
2             2       False       False      False        False          3.0
3             3        True       False       True        False          2.0
4             4       False        True      False        False         31.0
..          ...         ...         ...        ...          ...          ...
145         145       False        True       True        False         18.0
146         146        True       False      False        False          1.0
147         147        True        True       True         True         93.0
148         148        True        True      False        False          5.0
149         149        True        True       True         True        100.0

     aggregateLikes      id  \
0                 3  633998
1                 1  634426
2                 1  635085
3                 1  663229
4                 3  651437
..              ...     ...
145              13  638315
146               2  656248
147               2  637297
148               1  659412
149               4  647875

                                                 title  pricePerServing  ...  \
0                            Banana Blueberry Pancakes            55.79  ...
1              Basil and Orange Confit Compound Butter            15.07  ...
2                             Black Bottom Banana Bars            78.85  ...
3                  The Best Raw Chocolate Chip Cookies            54.64  ...
4                  Mediterranean Spinach Artichoke Dip           115.26  ...
..                                                 ...              ...  ...
145       Chicken Sausage, White Bean and Cabbage Soup           196.23  ...
146                                Pinot Noir Brownies            65.76  ...
147                          Cauliflower Chickpea Stew           139.28  ...
148  Saut√©ed Balsamic Green Beans With Cherry Tomatoes           101.81  ...
149        Indian-Style Dill and Turmeric Potato Salad           117.24  ...

     MagnesiumAmount  MagnesiumpercentOfDailyNeed IronAmount  \
0              19.91                         4.98       0.75
1                NaN                          NaN        NaN
2              43.70                        10.93       3.14
3               8.51                         2.13       1.21
4              42.27                        10.57       1.48
..               ...                          ...        ...
145            53.40                        13.35       3.34
146            33.91                         8.48       1.13
147           162.82                        40.71       4.85
148            35.26                         8.82       1.65
149             7.36                         1.84       0.99

     IronpercentOfDailyNeed  CopperAmount  CopperpercentOfDailyNeed  \
0                      4.14          0.08                      3.80
1                       NaN           NaN                       NaN
2                     17.46          0.26                     13.10
3                      6.71          0.03                      1.65
4                      8.23          0.13                      6.39
..                      ...           ...                       ...
145                   18.53          0.21                     10.62
146                    6.28          0.28                     14.15
147                   26.92          0.68                     34.15
148                    9.18          0.13                      6.71
149                    5.49          0.02                      1.18

     VitaminB1Amount  VitaminB1percentOfDailyNeed  CalciumAmount  \
0               0.03                         2.26          18.11
1                NaN                          NaN            NaN
2               0.32                        21.09         100.80
3               0.10                         6.47          26.79
4               0.07                         4.64         162.84
..               ...                          ...            ...
145             0.15                        10.23         102.67
146             0.03                         1.68          19.82
147             0.45                        29.70         141.16
148             0.12                         7.85          55.64
149              NaN                          NaN          27.96

     CalciumpercentOfDailyNeed
0                         1.81
1                          NaN
2                        10.08
3                         2.68
4                        16.28
..                         ...
145                      10.27
146                       1.98
147                      14.12
148                       5.56
149                       2.80

[150 rows x 53 columns]

#### Print the title of the recipes that are vegetarian == TRUE and glutenFree == True

In [62]:
mask1 = df['vegetarian'] == True
mask2 = df['glutenFree'] == True
df_ = df[mask1 & mask2]
print(df_["title"])

0                              Banana Blueberry Pancakes
1                Basil and Orange Confit Compound Butter
14                            Spicy Carrot Amaranth Soup
15                                            Nutty Rice
20                           Fire Roasted Tomato Chutney
22                                 Butternut Squash Soup
24                         Green Beans with Garlic Chips
27                                Easy Eggplant Parmesan
29                                            Kappa Maki
30                              Vegan Chana Masala Curry
31     Grilled Peach Melba with Vanilla Bean Frozen Y...
33                             Detox Orange Carrot Juice
37                      Roasted Asparagus with Egg Salad
39                   Three Ingredient Frozen Pina Colada
42                               Peach Coconut Ice Cream
57     Saut√©ed Balsamic Green Beans With Cherry Tomatoes
61                              Ginger Melon Side Salad
69                      Chicken with Avocado Peach Salsa
72                             EASY, CUMIN-LENTIL SPREAD
80                                 Luscious Palak Paneer
85                                             Beet Slaw
93             Roasted Strawberry Coconut Milk Ice Cream
96                                    Breakfast Porridge
97     Peanut Butter Cookies with Flax Seeds and Choc...
100                                  Blender Carrot Soup
101                                      Dandelion pesto
102                                Coconut Flour Muffins
106                              Japanese Cucumber Salad
107                           Blueberry Mojito Popsicles
119                                     Fried Brown Rice
123                                 Seasonal Autumn Stew
126    Slow Cooker Healthy Sweet Potato Soup with Coc...
129    Blueberry, Persimmon Smoothie with Banana and ...
131                              Mango Cranberry Sherbet
132                          Cherries and Yogurt Parfait
133                              The Pearhattan Cocktail
134            Garlic-Roasted Brussels Sprouts Side Dish
139                                  Layered Greek Salad
143                      Stir Fried Cabbage and Tomatoes
147                            Cauliflower Chickpea Stew
148    Saut√©ed Balsamic Green Beans With Cherry Tomatoes
149          Indian-Style Dill and Turmeric Potato Salad
Name: title, dtype: object

#### How many vegan recipes are there (Vegan = Vegetarian and dairy free)?

In [43]:
mask1 = df['vegetarian'] == True
mask2 = df["dairyFree"] == True
df_vegan = df[mask1 & mask2]
# print(df1)
print(f"Number of vegan recipes: {len(df_vegan)}")

Number of vegan recipes: 29

#### Compare the average amount of Vitamin B12 for the vegan and non-vegan recipes. How reliable are the results?

In [37]:
mask1 = df['vegetarian'] == True
mask2 = df["dairyFree"] == True
df_vegan = df[mask1 & mask2]
df_nonvegan = df[mask1 | mask2]
print('Vegan Mean for Vit B12:')
print(df_vegan['VitaminB12percentOfDailyNeed'].mean())
print('Non-Vegan Mean for Vit B12:')
print(df_nonvegan['VitaminB12percentOfDailyNeed'].mean())

Vegan Mean for Vit B12:
4.003333333333333
Non-Vegan Mean for Vit B12:
11.380217391304347

#### Compare the average health Score for both types of recipes (vegan vs non-vegan).

In [38]:
print("Average Health Score of Vegan recipes :")
print(df_vegan['healthScore'].mean())
print("Average Health Score of Non-Vegan recipes :")
print(df_nonvegan['healthScore'].mean())

Average Health Score of Vegan recipes :
27.724137931034484
Average Health Score of Non-Vegan recipes :
20.842105263157894

#### Create a new column: "VeganWeek" where you decrease the price of vegan products by 10%, but only if they already cost more than 100.

In [57]:

df_vegan['VeganWeek'] = np.where(df_vegan['pricePerServing'] > 100, df_vegan['pricePerServing'] - df_vegan['pricePerServing'] * 0.01,  df_vegan['pricePerServing'])
print(df_vegan)

     Unnamed: 0  vegetarian  glutenFree  dairyFree  veryHealthy  healthScore  \
0             0        True        True       True        False          1.0
3             3        True       False       True        False          2.0
9             9        True       False       True         True         62.0
14           14        True        True       True        False         16.0
20           20        True        True       True        False         20.0
29           29        True        True       True        False         19.0
30           30        True        True       True        False         17.0
33           33        True        True       True        False         54.0
39           39        True        True       True        False          7.0
61           61        True        True       True        False         13.0
69           69        True        True       True        False         11.0
72           72        True        True       True        False         49.0
73           73        True       False       True        False          2.0
93           93        True        True       True        False          4.0
97           97        True        True       True        False          2.0
101         101        True        True       True        False         10.0
102         102        True        True       True        False          1.0
106         106        True        True       True        False          7.0
107         107        True        True       True        False          3.0
119         119        True        True       True        False         30.0
123         123        True        True       True         True        100.0
126         126        True        True       True        False         21.0
129         129        True        True       True        False         14.0
133         133        True        True       True        False          7.0
134         134        True        True       True         True         77.0
138         138        True       False       True        False         12.0
143         143        True        True       True        False         50.0
147         147        True        True       True         True         93.0
149         149        True        True       True         True        100.0

     aggregateLikes       id  \
0                 3   633998
3                 1   663229
9                 1  1095768
14                2   661036
20                1   642892
29                1   648742
30                1  1096306
33                2   641443
39                6  1098357
61                1  1095692
69                0   673436
72                1   642154
73                1   644867
93                2   658665
97                1   655282
101             103   641227
102               1  1095713
106               1   648467
107               1   635495
119               1   643674
123               1   659689
126               1  1096231
129               1  1096178
133               6   663313
134               1  1096268
138               1   662315
143               6   661653
147               2   637297
149               4   647875

                                                 title  pricePerServing  ...  \
0                            Banana Blueberry Pancakes            55.79  ...
3                  The Best Raw Chocolate Chip Cookies            54.64  ...
9    Bulgur Wheat Salad with Chickpeas, Bell Pepper...           229.28  ...
14                          Spicy Carrot Amaranth Soup           220.53  ...
20                         Fire Roasted Tomato Chutney            74.69  ...
29                                          Kappa Maki            72.94  ...
30                            Vegan Chana Masala Curry           165.89  ...
33                           Detox Orange Carrot Juice           104.27  ...
39                 Three Ingredient Frozen Pina Colada           214.60  ...
61                            Ginger Melon Side Salad            219.70  ...
69                    Chicken with Avocado Peach Salsa            90.20  ...
72                           EASY, CUMIN-LENTIL SPREAD            29.56  ...
73                           Gluten-Free Baked Oatmeal            23.82  ...
93           Roasted Strawberry Coconut Milk Ice Cream           143.71  ...
97   Peanut Butter Cookies with Flax Seeds and Choc...            18.14  ...
101                                    Dandelion pesto           132.51  ...
102                              Coconut Flour Muffins            30.66  ...
106                            Japanese Cucumber Salad            29.96  ...
107                         Blueberry Mojito Popsicles           114.86  ...
119                                   Fried Brown Rice           188.92  ...
123                               Seasonal Autumn Stew           172.76  ...
126  Slow Cooker Healthy Sweet Potato Soup with Coc...           418.08  ...
129  Blueberry, Persimmon Smoothie with Banana and ...            48.70  ...
133                            The Pearhattan Cocktail           509.89  ...
134          Garlic-Roasted Brussels Sprouts Side Dish           170.34  ...
138  Sundried Tomato,Olive,Rosemary and Thyme Focca...            81.78  ...
143                    Stir Fried Cabbage and Tomatoes            80.89  ...
147                          Cauliflower Chickpea Stew           139.28  ...
149        Indian-Style Dill and Turmeric Potato Salad           117.24  ...

     VitaminB3percentOfDailyNeed  VitaminB1Amount VitaminB1percentOfDailyNeed  \
0                           2.44             0.03                        2.26
3                           3.26             0.10                        6.47
9                          27.55             0.37                       24.71
14                          5.94             0.09                        5.91
20                          4.50             0.06                        3.71
29                         10.15             0.19                       12.73
30                         10.71             0.20                       13.09
33                         13.26             0.35                       23.48
39                          5.25             0.19                       12.66
61                          8.02             0.15                        9.86
69                          8.04             0.06                        3.75
72                          7.19             0.24                       16.11
73                          1.48             0.09                        6.02
93                          4.14             0.03                        2.32
97                          7.68             0.04                        2.57
101                         1.47             0.10                        6.80
102                          NaN              NaN                         NaN
106                         1.20             0.03                        1.80
107                         1.35             0.02                        1.56
119                        35.32             0.42                       27.99
123                        30.77             0.38                       25.44
126                         9.99             0.26                       17.24
129                        14.85             0.06                        3.78
133                         5.44             0.10                        6.92
134                         6.13             0.23                       15.57
138                         9.99             0.46                       30.84
143                         7.02             0.19                       12.73
147                        23.83             0.45                       29.70
149                         1.05              NaN                         NaN

     CalciumAmount  CalciumpercentOfDailyNeed  AlcoholAmount  \
0            18.11                       1.81            NaN
3            26.79                       2.68            NaN
9           151.83                      15.18            NaN
14          103.27                      10.33            NaN
20           34.28                       3.43            NaN
29           21.56                       2.16            NaN
30          154.27                      15.43            NaN
33          168.53                      16.85            NaN
39           52.87                       5.29          13.36
61           31.29                       3.13            NaN
69           14.21                       1.42            NaN
72           32.02                       3.20            NaN
73           30.63                       3.06            NaN
93           26.76                       2.68            NaN
97           12.88                       1.29            NaN
101          19.65                       1.96            NaN
102            NaN                        NaN            NaN
106          19.32                       1.93            NaN
107          16.49                       1.65           1.25
119         140.79                      14.08            NaN
123         213.53                      21.35            NaN
126         104.01                      10.40            NaN
129          59.51                       5.95            NaN
133          63.01                       6.30          21.31
134          83.41                       8.34            NaN
138            NaN                        NaN            NaN
143         110.71                      11.07            NaN
147         141.16                      14.12            NaN
149          27.96                       2.80            NaN

     AlcoholpercentOfDailyNeed  CaffeineAmount  CaffeinepercentOfDailyNeed  \
0                          NaN             NaN                         NaN
3                          NaN             NaN                         NaN
9                          NaN             NaN                         NaN
14                         NaN             NaN                         NaN
20                         NaN             NaN                         NaN
29                         NaN             NaN                         NaN
30                         NaN             NaN                         NaN
33                         NaN             NaN                         NaN
39                       74.22             NaN                         NaN
61                         NaN             NaN                         NaN
69                         NaN             NaN                         NaN
72                         NaN             NaN                         NaN
73                         NaN             NaN                         NaN
93                         NaN             NaN                         NaN
97                         NaN             NaN                         NaN
101                        NaN             NaN                         NaN
102                        NaN             NaN                         NaN
106                        NaN             NaN                         NaN
107                       6.96             NaN                         NaN
119                        NaN             NaN                         NaN
123                        NaN             NaN                         NaN
126                        NaN             NaN                         NaN
129                        NaN             NaN                         NaN
133                     118.40             NaN                         NaN
134                        NaN             NaN                         NaN
138                        NaN             NaN                         NaN
143                        NaN             NaN                         NaN
147                        NaN             NaN                         NaN
149                        NaN             NaN                         NaN

     VeganWeek
0      55.7900
3      54.6400
9     226.9872
14    218.3247
20     74.6900
29     72.9400
30    164.2311
33    103.2273
39    212.4540
61    217.5030
69     90.2000
72     29.5600
73     23.8200
93    142.2729
97     18.1400
101   131.1849
102    30.6600
106    29.9600
107   113.7114
119   187.0308
123   171.0324
126   413.8992
129    48.7000
133   504.7911
134   168.6366
138    81.7800
143    80.8900
147   137.8872
149   116.0676

[29 rows x 80 columns]

<ipython-input-57-592efb65e48c>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_vegan['VeganWeek'] = np.where(df_vegan['pricePerServing'] > 100, df_vegan['pricePerServing'] - df_vegan['pricePerServing'] * 0.01,  df_vegan['pricePerServing'])

#### Among the non-vegan recipes, find the one requiring most time to prepare. How is it called?

In [84]:
mask1 = df['vegetarian'] == False
mask2 = df["dairyFree"] == False
df_nonvegan = df[mask1 & mask2]
df_nonvegan.sort_values(['readyInMinutes'], inplace=True, ascending=False)
print(df_nonvegan.head(1))

    Unnamed: 0  vegetarian  glutenFree  dairyFree  veryHealthy  healthScore  \
83          83       False       False      False        False          5.0

    aggregateLikes     id              title  pricePerServing  ...  \
83               0  45945  Oeufs En Meurette           209.85  ...

    VitaminB3Amount  VitaminB3percentOfDailyNeed VitaminB1Amount  \
83             1.51                         7.56            0.15

    VitaminB1percentOfDailyNeed  CalciumAmount  CalciumpercentOfDailyNeed  \
83                        10.13         124.54                      12.45

    AlcoholAmount  AlcoholpercentOfDailyNeed  CaffeineAmount  \
83            NaN                        NaN             NaN

    CaffeinepercentOfDailyNeed
83                         NaN

[1 rows x 79 columns]

<ipython-input-84-947a12032436>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_nonvegan.sort_values(['readyInMinutes'], inplace=True, ascending=False)